Repository CrayLabs/SmartSim, pull requests merged in 2021-08, with the labels that each got.

#72 Add condition to redis IP sleep
  smartsim/entity/dbnode.py
Labels: type: performance

#71 Documentation Update for 0.3.2
  CITATION.cff
  README.md
  doc/api/smartsim_api.rst
  doc/code_of_conduct.rst
  doc/community.rst
  doc/conf.py
  doc/developer.rst
  doc/experiment.rst
  doc/images/latticeboltzmann.png
  doc/index.rst
  doc/installation.rst
  doc/launchers.rst
  doc/overview.rst
  doc/requirements-doc.txt
  doc/tutorials/inference.rst
  doc/tutorials/lattice_boltz_analysis.rst
  doc/tutorials/using_clients.rst
  smart
  smartsim/database/cobaltOrchestrator.py
  smartsim/database/lsfOrchestrator.py
  smartsim/database/orchestrator.py
  smartsim/database/pbsOrchestrator.py
  smartsim/database/redis6.conf
  smartsim/database/slurmOrchestrator.py
  smartsim/entity/ensemble.py
  smartsim/experiment.py
  smartsim/settings/alpsSettings.py
  smartsim/settings/cobaltSettings.py
  smartsim/settings/lsfSettings.py
  smartsim/settings/mpirunSettings.py
  smartsim/settings/pbsSettings.py
  smartsim/settings/settings.py
  smartsim/settings/slurmSettings.py
  tests/on_wlm/test_launch_orc_cobalt.py
  tests/on_wlm/test_launch_orc_pbs.py
  tests/on_wlm/test_launch_orc_slurm.py
  tests/test_orchestrator.py
  tutorials/03_online_analysis/lattice/LICENSE
  tutorials/03_online_analysis/lattice/README.md
  tutorials/03_online_analysis/lattice/driver.py
  tutorials/03_online_analysis/lattice/fv_sim.py
  tutorials/cheyenne/README.md
Labels: area: docs

#73 Redis starter script for Orchestrator
  .github/workflows/release.yml
  README.md
  conftest.py
  doc/api/smartsim_api.rst
  doc/changelog.rst
  doc/conf.py
  doc/developer.rst
  doc/experiment.rst
  doc/installation.rst
  doc/launchers.rst
  doc/orchestrator.rst
  doc/overview.rst
  doc/tutorials/inference.rst
  requirements-dev.txt
  requirements.txt
  setup.cfg
  setup.py
  smart
  smartsim/bin/scripts/build-redis-ip.sh
  smartsim/bin/scripts/build-redis.sh
  smartsim/bin/smartsim_setup
  smartsim/config.py
  smartsim/control/controller.py
  smartsim/control/manifest.py
  smartsim/database/cobaltOrchestrator.py
  smartsim/database/lsfOrchestrator.py
  smartsim/database/orchestrator.py
  smartsim/database/pbsOrchestrator.py
  smartsim/database/redis_starter.py
  smartsim/database/slurmOrchestrator.py
  smartsim/entity/dbnode.py
  smartsim/entity/ensemble.py
  smartsim/entity/model.py
  smartsim/experiment.py
  smartsim/launcher/slurm/slurm.py
  smartsim/launcher/step/lsfStep.py
  smartsim/settings/alpsSettings.py
  smartsim/settings/cobaltSettings.py
  smartsim/settings/lsfSettings.py
  smartsim/settings/mpirunSettings.py
  smartsim/settings/pbsSettings.py
  smartsim/settings/settings.py
  smartsim/settings/slurmSettings.py
  smartsim/tf/utils.py
  smartsim/utils/helpers.py
  tests/full_wlm/test_launch_orc_lsf_batch.py
  tests/full_wlm/test_launch_orc_slurm_batch.py
  tests/on_wlm/test_launch_orc_cobalt.py
  tests/on_wlm/test_launch_orc_lsf.py
  tests/on_wlm/test_launch_orc_pbs.py
  tests/on_wlm/test_launch_orc_slurm.py
  tests/test_config.py
  tests/test_controller_errors.py
  tests/test_lsf_orc.py
  tests/test_orchestrator.py
  tutorials/cheyenne/README.md
  tutorials/cheyenne/launch_database_cluster.py
  tutorials/cheyenne/launch_multiple.py
  tutorials/cheyenne/run.sh
Labels: area: orchestrator, type: feature, type: refactor

#77 Installation doc and test fixes
  config.toml
  doc/installation.rst
  smartsim/database/cobaltOrchestrator.py
  smartsim/database/pbsOrchestrator.py
  smartsim/database/slurmOrchestrator.py
  tests/test_orchestrator.py
Labels: area: test, area: docs

#76 Add new FindTensorFlow.cmake
  conftest.py
  doc/installation.rst
  doc/orchestrator.rst
  modules/FindTensorFlow.cmake
  smartsim/bin/scripts/build-redisai-cpu.sh
  smartsim/bin/scripts/build-redisai-gpu.sh
  smartsim/database/redis6.conf
  smartsim/launcher/lsf/lsfLauncher.py
  tutorials/cheyenne/launch_database_cluster.py
  tutorials/summit/README.md
  tutorials/summit/hello.c
  tutorials/summit/launch_database_cluster.py
  tutorials/summit/launch_distributed_model_lsf.py
  tutorials/summit/launch_distributed_model_ompi.py
  tutorials/summit/run.sh
Labels: area: third-party, type: feature
