Repository CrayLabs/SmartSim, pull requests merged in 2023-09, with the labels that each got.

#358 Remove references in docs to nonexistent CLI flag
  doc/installation_instructions/site-install.rst
  tutorials/ml_inference/Inference-in-SmartSim.ipynb
Labels: area: docs

#359 Pretty print error message when onnx wheel not available
  smartsim/_core/_cli/build.py
Labels: area: build

#360 Update `cibuildwheel` version
  .github/workflows/release.yml
Labels: area: CI/CD

#361 Update changelog for release
  doc/changelog.rst
Labels: area: docs

#362 Version Bump
  .wci.yml
  doc/conf.py
  doc/installation_instructions/platform/olcf-summit.rst
  docker/dev/Dockerfile
  docker/prod/Dockerfile
  smartsim/_core/_install/buildenv.py
Labels: area: build, area: docs

#370 Update version names for v0.5.1
  .gitignore
  doc/_static/version_names.json
Labels: area: docs

#355 Send shutdown command to DB
  conftest.py
  smartsim/_core/control/controller.py
  smartsim/_core/utils/redis.py
  smartsim/database/orchestrator.py
  smartsim/experiment.py
  smartsim/settings/palsSettings.py
  tests/backends/test_dbmodel.py
  tests/test_configs/cov/local_cov.cfg
Labels: area: test, area: orchestrator, type: feature

#372 Publish artifacts from test_output on CI fail
  .github/workflows/run_tests.yml
Labels: area: test, area: CI/CD

#374 Fix broken 'Install' link in README
  README.md
Labels: area: docs

#378 Make `EntityList` a generic collection
  smartsim/_core/control/controller.py
  smartsim/_core/control/job.py
  smartsim/_core/control/jobmanager.py
  smartsim/_core/control/manifest.py
  smartsim/_core/generation/generator.py
  smartsim/database/orchestrator.py
  smartsim/entity/__init__.py
  smartsim/entity/ensemble.py
  smartsim/entity/entity.py
  smartsim/entity/entityList.py
  tests/test_configs/cov/cobalt_cov.cfg
  tests/test_configs/cov/local_cov.cfg
  tests/test_configs/cov/lsf_cov.cfg
  tests/test_configs/cov/pbs_cov.cfg
  tests/test_configs/cov/slurm_cov.cfg
Labels: area: api
