Repository CrayLabs/SmartSim, pull requests merged in 2024-06, with the labels that each got.

#581 Removal of Factory Methods from Experiment API
  smartsim/experiment.py
Labels: ignore-for-release

#603 Job and MPMD Job Implementation
  smartsim/launchable/__init__.py
  smartsim/launchable/basejob.py
  smartsim/launchable/job.py
  smartsim/launchable/launchable.py
  smartsim/launchable/mpmdjob.py
  smartsim/launchable/mpmdpair.py
  tests/_legacy/test_launchable.py
Labels: ignore-for-release

#609 Fine Grain GPU Build Options
  README.md
  doc/changelog.md
  doc/installation_instructions/basic.rst
  doc/requirements-doc.txt
  doc/tutorials/ml_inference/Inference-in-SmartSim.ipynb
  smartsim/_core/_cli/build.py
  smartsim/_core/_cli/validate.py
  smartsim/_core/_install/buildenv.py
  smartsim/_core/_install/builder.py
  smartsim/_core/types.py
  smartsim/entity/dbobject.py
  smartsim/entity/ensemble.py
  smartsim/entity/model.py
  tests/install/test_builder.py
Labels: area: build

#599 BaseJobGroup, JobGroup, ColocatedJobGroup skeleton
  smartsim/launchable/__init__.py
  smartsim/launchable/baseJobGroup.py
  smartsim/launchable/basejob.py
  smartsim/launchable/colocatedJobGroup.py
  smartsim/launchable/jobGroup.py
  smartsim/launchable/mpmdpair.py
  tests/temp_tests/test_colocatedJobGroup.py
  tests/temp_tests/test_jobGroup.py
  tests/temp_tests/test_launchable.py
Labels: type: feature, ignore-for-release

#618 Add 'f' to f-strs
  doc/changelog.md
  smartsim/_core/_install/builder.py
Labels: type: chore, short task
