Repository CrayLabs/SmartSim, pull requests merged in 2024-02, with the labels that each got.

#472 Add eval() to remove Torch warnings during testing
  doc/changelog.rst
  tests/backends/test_dbmodel.py
Labels: area: test

#476 Manifest: has DB objects refactor
  smartsim/_core/control/manifest.py
  tests/test_manifest.py
Labels: type: refactor

#473 Use developer log level, protect logger defaults in test
  smartsim/log.py
  tests/test_logs.py
Labels: bug: minor, Short task, type: bug

#493 Hot Fix: bump dependency version
  .wci.yml
  Makefile
  doc/_static/version_names.json
  doc/changelog.rst
  doc/conf.py
  doc/installation_instructions/platform/olcf-summit.rst
  docker/prod/Dockerfile
  smartsim/_core/_install/buildenv.py
Labels: area: third-party, bug: critical

#501 Change generic t.any in Experiment API
  doc/changelog.rst
  smartsim/experiment.py
Labels: area: api
