Repository CrayLabs/SmartSim, pull requests merged in 2024-01, with the labels that each got.

#453 Override sphinx-tabs background color
  doc/_static/custom_tab_style.css
  doc/changelog.rst
  doc/conf.py
Labels: area: docs

#451 Upgrade Machine Learning Dependencies
  .github/workflows/run_tests.yml
  README.md
  doc/changelog.rst
  doc/installation_instructions/basic.rst
  doc/ml_features.rst
  doc/requirements-doc.txt
  smartsim/_core/_cli/build.py
  smartsim/_core/_install/buildenv.py
  smartsim/_core/_install/builder.py
  tests/install/test_buildenv.py
  tests/install/test_builder.py
  tutorials/ml_inference/Inference-in-SmartSim.ipynb
  tutorials/online_analysis/lattice/online_analysis.ipynb
Labels: area: build, area: ML

#458 Quality of life `smart validate` Improvements
  smartsim/_core/_cli/validate.py
  tests/test_cli.py
Labels: type: usability

#461 Python 3.11 Support
  .github/workflows/run_tests.yml
  doc/changelog.rst
  doc/installation_instructions/basic.rst
  setup.cfg
  tests/test_logs.py
Labels: area: build, area: third-party, type: usability

#459 Relax typing extensions required version
  setup.py
Labels: area: build, area: third-party

#468 Expose SS Typehints
  pyproject.toml
  setup.cfg
  smartsim/_core/utils/redis.py
  smartsim/database/orchestrator.py
  smartsim/entity/dbobject.py
  smartsim/entity/ensemble.py
  smartsim/entity/model.py
  smartsim/ml/data.py
  smartsim/ml/tf/data.py
  smartsim/py.typed
Labels: area: api, type: usability
